version: "2"
services:
  phonebook:
    build: './phonebook'
    image: phonebook
    depends_on: 
      - cassandra1
    links:
      - cassandra1
    ports:
      - 8080:8080
    environment:
      CASSANDRA_USER_NAME: cassandra
      CASSANDRA_PASSWORD: cassandra
      KEYSPACE: usersks
      TABLENAME: phonebook
      HOSTS: 'cassandra1,cassandra2,cassandra3'
  cassandra1:
    build: .
    image: cassandralogin
    ports:
      - 9042:9042 
      - 9160:9160
  cassandra2:
    image: cassandralogin
    depends_on:
      - cassandra1
    ports:
      - 9042    
    environment:
      CASSANDRA_SEEDS: cassandra1
  cassandra3:
    image: cassandralogin
    depends_on:
      - cassandra1
    ports:
      - 9042   
    environment:
      CASSANDRA_SEEDS: cassandra1      
