version: "2"
services:
  cassandra1:
    build: .
    image: cassandralogin
    ports:
      - 9042:9042 
      - 9160:9160
  cassandra2:
    image: cassandralogin
    depends_on:
      - cassandra1
    links:
      - cassandra1
    ports:
      - 9042    
    environment:
      CASSANDRA_SEEDS: cassandra1
  cassandra3:
    image: cassandralogin
    depends_on:
      - cassandra1
    links:
      - cassandra1 
    ports:
      - 9042   
    environment:
      CASSANDRA_SEEDS: cassandra1      
